- id: prevent-poetry-downgrade
  name: prevent poetry.lock downgrade
  description: Compares the Poetry version used for locking against HEAD.
  entry: prevent-poetry-downgrade
  language: python
  files: poetry.lock
  pass_filenames: true
