- id: prevent-poetry-downgrade
  name: prevent poetry.lock downgrade
  description: Compares the Poetry version used for locking against HEAD.
  entry: prevent_poetry_downgrade.py
  language: python
  files: poetry.lock
  pass_filenames: true
  types: [python]
